#ifndef APP_BACK_INC_AUTONOMOUS_H_
#define APP_BACK_INC_AUTONOMOUS_H_

#include <can.h>
#include <pin.h>

typedef enum MmrAutonomousState {
  MMR_AUTONOMOUS_LAUNCH_WAITING,
  MMR_AUTONOMOUS_LAUNCH_PULL_CLUTCH,
  MMR_AUTONOMOUS_LAUNCH_WAIT_BEFORE_CHANGING_GEAR,

  MMR_AUTONOMOUS_LAUNCH_CHANGE_GEAR,
  MMR_AUTONOMOUS_LAUNCH_SET_LAUNCH_CONTROL,
  MMR_AUTONOMOUS_LAUNCH_WAIT_BEFORE_ACCELERATING,

  MMR_AUTONOMOUS_LAUNCH_ACCELERATE,
  MMR_AUTONOMOUS_LAUNCH_RELEASE_CLUTCH,
  MMR_AUTONOMOUS_LAUNCH_UNSET_LAUNCH,
  MMR_AUTONOMOUS_LAUNCH_ACCELERATE_TO_15,
  MMR_AUTONOMOUS_LAUNCH_ACCELERATE_TO_MINIMUM,

  MMR_AUTONOMOUS_LAUNCH_CLUTCH_SET_MANUAL,
  MMR_AUTONOMOUS_LAUNCH_SET_MANUAL_APPS,
  MMR_AUTONOMOUS_LAUNCH_DONE,
} MmrAutonomousState;


MmrAutonomousState MMR_AUTONOMOUS_LAUNCH_Run(MmrAutonomousState state);

#endif // !APP_BACK_INC_AUTONOMOUS_H_
