#ifndef APP_CORE_BACK_INC_EBS_CHECK_H_
#define APP_CORE_BACK_INC_EBS_CHECK_H_

#include <stdbool.h>


typedef enum MmrEbsState {
  MMR_EBS_ACTIVATED,
} MmrEbsState;

typedef enum MmrEbsCheckState {
  EBS_CHECK_START_WATCHDOG,
  EBS_CHECK_SDC_WAIT_HIGH,
  EBS_CHECK_STOP_WATCHDOG,
  EBS_CHECK_SDC_WAIT_LOW,
  EBS_CHECK_RETOGGLE_WATCHDOG,

  EBS_CHECK_EBS_PRESSURE_OK,
  EBS_CHECK_BRAKE_PRESSURE_OK,

  EBS_CHECK_ACTIVATE_TS,
  EBS_CHECK_WAIT_TS_ACTIVATION,

  EBS_CHECK_DISABLE_ACTUATOR_1,
  EBS_CHECK_CHECK_ACT_1_BRAKE_PRESSURE,
  EBS_CHECK_ENABLE_ACTUATOR_1,

  EBS_CHECK_DISABLE_ACTUATOR_2,
  EBS_CHECK_CHECK_ACT_2_BRAKE_PRESSURE,
  EBS_CHECK_ENABLE_ACTUATOR_2,

  EBS_CHECK_READY,
  EBS_CHECK_ERROR,
} MmrEbsCheckState;


typedef enum MmrEbsDrivingMode {
  MMR_EBS_CHECK_DRIVING_MODE_MANUAL,
  MMR_EBS_CHECK_DRIVING_MODE_AUTONOMOUS,
} MmrEbsDrivingMode;

void MMR_EBS_CHECK_Arm();
void MMR_EBS_CHECK_Disarm();
void MMR_EBS_CHECK_SetDrivingMode(MmrEbsDrivingMode mode);
bool MMR_EBS_CHECK_SdcIsReady();

#endif // !APP_CORE_BACK_INC_EBS_CHECK_H_
