#ifndef APP_CORE_BACK_INC_EBS_H_
#define APP_CORE_BACK_INC_EBS_H_

#include <stdbool.h>


typedef enum MmrEbsState {
  EBS_START_WATCHDOG,
  EBS_SDC_WAIT_HIGH,
  EBS_STOP_WATCHDOG,
  EBS_SDC_WAIT_LOW,
  EBS_RETOGGLE_WATCHDOG,

  EBS_EBS_PRESSURE_OK,
  EBS_BRAKE_PRESSURE_OK,

  EBS_ACTIVATE_TS,
  EBS_WAIT_TS_ACTIVATION,

  EBS_DISABLE_ACTUATOR_1,
  EBS_CHECK_ACT_1_BRAKE_PRESSURE,
  EBS_ENABLE_ACTUATOR_1,

  EBS_DISABLE_ACTUATOR_2,
  EBS_CHECK_ACT_2_BRAKE_PRESSURE,
  EBS_ENABLE_ACTUATOR_2,

  EBS_READY,
  EBS_ERROR,
} MmrEbsState;


typedef enum MmrEbsDrivingMode {
  MMR_EBS_DRIVING_MODE_MANUAL,
  MMR_EBS_DRIVING_MODE_AUTONOMOUS,
} MmrEbsDrivingMode;

void MMR_EBS_Arm();
void MMR_EBS_Disarm();
void MMR_EBS_SetDrivingMode(MmrEbsDrivingMode mode);
bool MMR_EBS_SdcIsReady();

#endif // !APP_CORE_BACK_INC_EBS_H_
